#
#                  Nmake File For Utility Routines
#
!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG=1
!ENDIF


!include <ntwin32.mak>

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

OBJS =  ahputaway.obj \
	brent.obj \
	butterworth.obj \
	chron3.obj \
	complex_math.obj \
	convertInstResponse.obj \
	earthworm_defs.obj \
	ew_spectra_io.obj \
	ew_nevent_message.obj \
	fft99.obj \
	fft_prep.obj \
	fleng.obj \
	global_loc_rw.obj \
	global_pick_rw.obj \
	global_amp_rw.obj \
	global_msg.obj \
	gma.obj \
	geo_to_km.obj \
	getutil.obj \
	glevt_2_ewevent.obj \
	gseputaway.obj \
	k2evt2ew.obj \
	kom.obj \
	ioc_filter.obj \
	logit.obj \
	logit_mt.obj \
	lockfile.obj \
	make_triglist.obj \
	mask_check.obj \
	mem_circ_queue.obj \
	mnbrak.obj \
	mseedputaway.obj \
	neic2scn.obj \
	parse_trig.obj \
	parse_usnsn.obj \
	priority_queue.obj \
	psn4putaway.obj \
	putaway.obj \
	rdpickcoda.obj \
	read_arc.obj \
	residue.obj \
	rw_coda_aav.obj \
	rw_mag.obj \
	rw_strongmotion.obj \
	rw_strongmotionII.obj \
	sacputaway.obj \
	seiputaway.obj \
	seiutils.obj \
	site.obj \
	socket_ew_common.obj \
        sqlite3.obj \
	startstop_lib.obj \
	sudsputaway.obj \
	swap.obj \
	tankputaway.obj \
	tlay.obj \
	transfer.obj \
 	transferFunction.obj \
 	xfrm.obj \
	trheadconv.obj \
	watchdog_client.obj \
	wave_client.obj \
	wfdiscputaway.obj \
	ws_clientII.obj \
	ws_clientIIx.obj \
	ws_clientII_no_location.obj \
	ws2ts.obj \
	nordic.obj



all: $(OBJS) install

logit_mt.obj: logit.c
   $(CC) $(GLOBALFLAGS)  /Fologit_mt.obj /D_LOGITMT $(cflags) $(cdebug) $(cvarsmt) \
         $(tflags) logit.c

.c.obj:
   $(CC) $(GLOBALFLAGS)  /nologo $(cflags) $(cdebug) /D_INTEL $(cvarsmt) $(tflags) $<

install:
   copy *.obj $L
	 nmake -a -f makefile.nt gd_lib


gd_lib:
	nt_comp gd_lib

clean:
	-del core *.o *.obj *% *~ ..\..\..\lib\libmseed.lib
	nt_clean libmseed gd_lib


