#
#                           Nmake File For sendfile_srv
#                             Windows NT version
#
!include <ntwin32.mak>

APP=sendfile_srv
O=$(APP).obj socket_win.obj config.obj chdir_win.obj getfname_win.obj \
  sleep_win.obj log.obj tzset_win.obj fopen_win.obj

compflags= /c /W3 /MT /nologo

linkflags= /release /nologo

libs= libcmt.lib ws2_32.lib

all: $(APP).exe

$(APP).exe: $O
   link $(linkflags) $(libs) $O -out:$(APP).exe

.c.obj:
   $(CC) $(GLOBALFLAGS)  $(compflags) $(tflags) $<

clean:
   -del *.o *.obj $(APP).exe
