#
#
#
#
#                    Nmake File For nq2wws_ack - Windows NT version
#
#    !!! Dummy makefile. A Windows wonk needs to add QLIB and make this work.  Jim.

NODEBUG=1

!include <ntwin32.mak>

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib


all:
	emake nq2wws_ack


export_ack: nq2wws_ack.obj  
    $(link) $(conlflags) $(ldebug) $(conlibsmt) nq2wws_ack.obj \
    $L\mem_circ_queue.obj $L\getsysname_ew.obj \
    $L\libew_mt.lib $L\socket_ew.obj $L\socket_ew_common.obj \
     -out:$B\nq2wws_ack.exe


.c.obj:
   $(CC) $(GLOBALFLAGS)  /nologo $(cflags) $(cdebug) $(cvarsmt) $(tflags) $<


# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~

clean_bin:
	-del $B\export_generic* $B\export_scnl* $B\export*actv* $B\export*ack*
