#
#
# Nmake File For libmseed - MS Visual C++ version
# Use 'nmake -f Makefile.win'
#
# File Makefile.nt is modified for Earthworm
#

NODEBUG=1

!include <ntwin32.mak>

L = $(EW_HOME)\$(EW_VERSION)\lib
I = $(EW_HOME)\$(EW_VERSION)\include

INCS = -I.
OPTS = -D_CRT_SECURE_NO_WARNINGS
LIB = libmseed.lib
DLL = libmseed.dll

OBJS=	fileutils.obj	\
	genutils.obj	\
	gswap.obj	\
	lmplatform.obj	\
	lookup.obj	\
	msrutils.obj	\
	pack.obj	\
	packdata.obj	\
	traceutils.obj	\
	tracelist.obj	\
	parseutils.obj	\
	unpack.obj	\
	unpackdata.obj  \
	selection.obj	\
	logging.obj

all: lib install

lib: $(OBJS)
	link.exe /lib /nologo /out:$(LIB) $(OBJS)

dll: $(OBJS)
	link.exe /dll /nologo /out:$(DLL) $(OBJS)

.c.obj:
	$(cc) /nologo $(cflags) $(GLOBALFLAGS) $(cdebug) $(cvarsmt) $(tflags) $(INCS) $(OPTS) $<


# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~ $(LIB) $(DLL)

install: libmseed.lib libmseed.h lmplatform.h
	copy libmseed.lib $L
	copy libmseed.h $I
	copy lmplatform.h $I
