#
# Dummy makefile - only used for cleaning things up
#

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib



# Clean-up rules
clean:
	-del a.out core *.o *.obj *% *~

clean_bin:
	-del $B\geojson2ew*
