#
#                    Nmake File For ew2ssam  - Windows NT version
#
NODEBUG=1

!include <ntwin32.mak>

APP = ew2ssam
O = $(APP).obj 

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

$B\$(APP).exe: $O
   $(link) $(conlflags) $(ldebug) $(conlibsmt) $O \
    $L\swap.obj $L\mem_circ_queue.obj $L\libew_mt.lib \
    -out:$B\$(APP).exe

.c.obj:
   $(CC) $(GLOBALFLAGS)  /nologo $(cflags) $(cdebug) $(cvarsmt) $(tflags) $<


# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~

clean_bin:
	-del $B\ew2ssam*
