LINUX_FLAGS=-lpthread -lm
SOLARIS_FLAGS=-lposix4
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = ${GLOBALFLAGS}

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

OBJFILES = $L/errexit.o $L/mem_circ_queue.o $L/libew_mt.a

sniffrings: sniffrings.o $(OBJFILES)
	$(CC) $(CFLAGS) -o $B/sniffrings sniffrings.o $(OBJFILES) $(SPECIFIC_FLAGS)

lint:
	lint sniffrings.c $(GLOBALFLAGS)

# Clean-up rules
clean:
	rm -f a.out core *.o *.obj *% *~

clean_bin:
	rm -f $B/sniffrings*
