#
#   This file is managed using Concurrent Versions System (CVS).
#
#    $Id: makefile.nt 5320 2013-01-30 20:04:07Z tim $
#
#    Revision history:
#     $Log$
#     Revision 1.9  2010/04/13 05:57:54  paulf
#     added scnl2scn removal to clean_nt_bin
#
#     Revision 1.8  2007/01/11 23:26:45  dietz
#     cleaned up Windows compile warnings/errors after Lombard's full SCNL->SCN
#     remapping modifications to scnl2scn.
#
#     Revision 1.7  2006/12/28 23:27:53  lombard
#     Added version number, printed on startup.
#     Revised scnl2scn to provide complete mapping from SCNL back to SCN, using
#     configuration command similar to scn2scnl.
#
#     Revision 1.6  2006/11/21 23:03:33  stefan
#     GLOBALFLAGS for c compiler from ew_nt.cmd
#
#     Revision 1.5  2006/11/21 22:22:54  stefan
#     cl to $(CC) $(GLOBALFLAGS)  and include <ntwin32.mak>
#
#     Revision 1.4  2005/02/15 16:54:06  davidk
#     Added rdpickcoda.obj to the list of library object dependencies for scn_convert,
#     as it appeared to be needed.
#
#     Revision 1.3  2004/10/19 21:54:04  lombard
#     Changes to support rules for renaming specific and wild-carded SCNs to
#     configured SCNLs.
#
#     Revision 1.2  2004/05/26 15:36:18  kohler
#     Added support for pick and coda conversion.
#
#     Revision 1.1  2004/05/18 22:57:30  kohler
#     Initial entry into CVS.
#
#     Revision 1.1.1.1  2004/05/18 16:33:18  kohler
#     initial import into CVS
#
#
#                   Nmake File For scn2scnl and scnl2scn
#                           Windows NT version
#
!include <ntwin32.mak>

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

compflags= /c /W3 /MT /nologo
linkflags= /release /nologo
libs= libcmt.lib ws2_32.lib

all:
   emake $B\scn2scnl.exe
   emake $B\scnl2scn.exe

scn2scnl:
   emake $B\scn2scnl.exe

scnl2scn:
   emake $B\scnl2scn.exe

$B\scn2scnl.exe: scn2scnl.obj scn_config.obj to_pick_scnl.obj \
   to_coda_scnl.obj scn_convert.obj to_trace_scnl.obj
   link $(linkflags) $(libs) scn2scnl.obj scn_config.obj to_pick_scnl.obj \
   to_coda_scnl.obj scn_convert.obj to_trace_scnl.obj \
   $L\libew.lib  $L\trheadconv.obj $L\rdpickcoda.obj \
   -out:$B\scn2scnl.exe

$B\scnl2scn.exe: scnl2scn.obj scnl_config.obj to_pick2k.obj \
   to_coda2k.obj scnl_convert.obj to_trace_scn.obj
   link $(linkflags) $(libs) scnl2scn.obj scnl_config.obj to_pick2k.obj \
   to_coda2k.obj scnl_convert.obj to_trace_scn.obj \
   $L\libew.lib $L\rdpickcoda.obj \
   -out:$B\scnl2scn.exe

.c.obj:
   $(CC) $(GLOBALFLAGS)  $(compflags) $(tflags) $<


# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~

clean_bin:
	-del $B\scn2scnl* $B\scnl2scn*
