#
#                    Nmake File For startstop_nt
#
NODEBUG=1

!include <ntwin32.mak>

APP1=ew_nevent_test_sender 
APP2=ew_nevent_test_receiver

B = .
L = $(EW_HOME)\$(EW_VERSION)\lib
O=$(APP1).obj
O2=$(APP2).obj

all: $B\$(APP1).exe $B\$(APP2).exe


$B\$(APP1).exe: $O
   $(link) $(conlflags) $(ldebug) $(conlibsmt) $O \
   $L\sema_ew.obj\
   $L\libew_mt.lib $L\startstop_lib.obj \
    $L\startstop_winlib.obj $L\service_ew.obj $L\lockfile.obj $L\lockfile_ew.obj \
    $L\ew_nevent_message.obj  -out:$B\$(APP1).exe

$B\$(APP2).exe: $(O2)
   $(link) $(conlflags) $(ldebug) $(conlibsmt) $(O2) \
   $L\sema_ew.obj\
   $L\libew_mt.lib $L\startstop_lib.obj \
    $L\startstop_winlib.obj $L\service_ew.obj $L\lockfile.obj $L\lockfile_ew.obj \
    $L\ew_nevent_message.obj  -out:$B\$(APP2).exe


.c.obj:
   $(CC) $(GLOBALFLAGS)  /nologo $(cflags) $(cdebug) $(cvarsmt) $(tflags) $<

# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~

clean_bin:
	-del $B\startstop*
