#
#
# Nmake File - MS Visual C++ version
# Use 'nmake -f Makefile.win'

NODEBUG=1

!include <ntwin32.mak>

L = $(EW_HOME)\$(EW_VERSION)\lib

INCS = /I.
LIB = libdali.lib
DLL = libdali.dll

OBJS=	timeutils.obj	\
	genutils.obj	\
	strutils.obj	\
	logging.obj	\
	network.obj	\
	statefile.obj	\
	config.obj	\
	portable.obj	\
	connection.obj	

all: lib

lib: $(OBJS)
	link.exe /lib /nologo /out:$(LIB) $(OBJS)
	copy $(LIB) $(L)

dll: $(OBJS)
	link.exe /dll /nologo /out:$(DLL) $(OBJS)

.c.obj:
	$(cc) /nologo $(cflags) $(cdebug) $(cvarsmt) $(tflags) $(INCS) $<


# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~ $(LIB) $(DLL) $(L)\$(LIB)
