#
#                    Nmake File For wsv_test - Windows NT version
#
NODEBUG=1

!include <ntwin32.mak>

APP = wsv_test
O = $(APP).obj
B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

$B\$(APP).exe: $O
   $(link) $(conlflags) $(ldebug) $(conlibsmt) $O $L\socket_ew.obj $L\socket_ew_common.obj \
    $L\ws_clientII.obj \
    $L\libew.lib -out:$B\$(APP).exe

.c.obj:
   $(CC) $(GLOBALFLAGS)  $(cflags) $(cdebug) $(cvarsmt) $(tflags) $<

# Clean-up directives
clean:
	del a.out core *.o *.obj *% *~

clean_bin:
	del $B\$(APP)*
