#
#                    Nmake File For harley2hinv - Windows NT version
#
NODEBUG=1

!include <ntwin32.mak>

APP = harley2hinv

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

$B\$(APP).exe: $(APP).obj
   $(link) $(conlflags) $(ldebug) $(conlibsmt) $(APP).obj -out:$B\$(APP).exe

.c.obj:
   $(CC) $(GLOBALFLAGS)  /nologo $(cflags) $(cdebug) $(cvarsmt) $(tflags) $<

# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~

clean_bin:
	-del $B\harley2hinv*
