#
#                           Nmake File For snwclient
#                             Windows NT version
#
NODEBUG=1

!include <ntwin32.mak>

APP = snwclient
O = $(APP).obj socket_win.obj config.obj chdir_win.obj getfname_win.obj \
    sleep_win.obj log.obj tzset_win.obj fopen_win.obj

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

$B\$(APP).exe: $O
   $(link) $(conlflags) $(ldebug) $(conlibsmt) $O $L\libew.lib -out:$B\$(APP).exe

.c.obj:
   $(CC) $(GLOBALFLAGS) /nologo $(cflags) $(cdebug) $(cvarsmt) $(tflags) $<

# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~

clean_bin:
	-del $B\$(APP).exe
