
#
#

LINUX_FLAGS=-lpthread
SOLARIS_FLAGS=-lposix4
SPECIFIC_FLAGS=$($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib


BINARIES = tankplayer.o $L/libew.a $L/swap.o $L/dirops_ew.o

tankplayer: $(BINARIES)
	$(CC) -o $B/tankplayer ${CFLAGS} $(BINARIES) $(SPECIFIC_FLAGS)

lint:
	lint tankplayer.c $(GLOBALFLAGS)


# Clean-up rules
clean:
	rm -f a.out core *.o *.obj *% *~

clean_bin:
	rm -f $B/tankplayer*
