#                    Make file for getfile_cl
#

LINUX_FLAGS=
SOLARIS_FLAGS=-lsocket -lnsl -lposix4
SPECIFIC_FLAGS=$($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS) -g

O = getfile_cl.o config.o socket_lnx.o chdir_sol.o rename_sol.o \
    sleep_sol.o log.o tzset_sol.o

all: getfile_cl

getfile_cl: $O
	$(CC) $(CFLAGS) -o getfile_cl $O -lm -lc $(SPECIFIC_FLAGS)

clean:
	-/bin/rm -f getfile_cl *.o

clean_bin:
	-/bin/rm -f getfile_cl 
