
DELIMITER $$
DROP FUNCTION IF EXISTS `fn_get_moledb_version_and_date`$$
CREATE  DEFINER = CURRENT_USER  FUNCTION `fn_get_moledb_version_and_date`(
) RETURNS VARCHAR(300) NOT DETERMINISTIC
BEGIN

  DECLARE RET    VARCHAR(300) DEFAULT '';

  SELECT CONCAT(version, ' ', CAST(release_date AS CHAR)) INTO RET FROM version;

  RETURN RET;

END$$
DELIMITER ;

