#
#
#          Nmake File For stopmodule - Windows NT version
#

NODEBUG=1

!include <ntwin32.mak>

APP = stopmodule
O = $(APP).obj

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib


$B\$(APP).exe: $O
   $(link) $(conlflags) $(ldebug) $(conlibsmt) $O $L\dirops_ew.obj \
   $L\libew.lib \
    -out:$B\$(APP).exe

.c.obj:
   $(CC) $(GLOBALFLAGS)  /nologo $(cflags) $(cdebug) $(cvarsmt) $(tflags) $<


# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~

clean_bin:
	-del $B\stopmodule*
