OBJ1     = remodl.o libtau.o libsun.o emiasp91.o
#
OBJ2    = setbrn.o libtau.o libsun.o
#
OBJ3    = ttimes.o libtau.o libsun.o
#
#
remodl: $(OBJ1)
	f77 $(OBJ1) -o remodl

setbrn: $(OBJ2)
	f77 $(OBJ2) -o setbrn

ttimes: $(OBJ3)
	f77 $(OBJ3) -o ttimes
