.TH "NMXP_MESSAGE_HEADER" 3 "Mon Jan 24 2011" "Version 1.2.4" "libnmxp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NMXP_MESSAGE_HEADER \- 
.PP
Header for all messages.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nmxp_data.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBsignature\fP"
.br
.ti -1c
.RI "int32_t \fBtype\fP"
.br
.ti -1c
.RI "int32_t \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header for all messages. 
.SH "Member Data Documentation"
.PP 
.SS "int32_t \fBNMXP_MESSAGE_HEADER::signature\fP"
.SS "int32_t \fBNMXP_MESSAGE_HEADER::type\fP"
.SS "int32_t \fBNMXP_MESSAGE_HEADER::length\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libnmxp from the source code.
