.TH "NMXP_CHAN_PRECISITEM" 3 "Mon Jan 24 2011" "Version 1.2.4" "libnmxp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NMXP_CHAN_PRECISITEM \- 
.PP
Precis Channel item.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nmxp_chan.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBkey\fP"
.br
.ti -1c
.RI "char \fBname\fP [12]"
.br
.ti -1c
.RI "int32_t \fBstart_time\fP"
.br
.ti -1c
.RI "int32_t \fBend_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Precis Channel item. 
.SH "Member Data Documentation"
.PP 
.SS "int32_t \fBNMXP_CHAN_PRECISITEM::key\fP"
.SS "char \fBNMXP_CHAN_PRECISITEM::name\fP[12]"
.SS "int32_t \fBNMXP_CHAN_PRECISITEM::start_time\fP"
.SS "int32_t \fBNMXP_CHAN_PRECISITEM::end_time\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libnmxp from the source code.
