.TH "NMXP_TM_T" 3 "Mon Jan 24 2011" "Version 1.2.4" "libnmxp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NMXP_TM_T \- 
.PP
struct tm plus ten thousandth second field  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nmxp_data.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct tm \fBt\fP"
.br
.ti -1c
.RI "uint32_t \fBd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct tm plus ten thousandth second field 
.SH "Member Data Documentation"
.PP 
.SS "struct tm \fBNMXP_TM_T::t\fP"
.SS "uint32_t \fBNMXP_TM_T::d\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libnmxp from the source code.
