.TH "NMXP_CHANNELINFOREQUEST" 3 "Mon Jan 24 2011" "Version 1.2.4" "libnmxp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NMXP_CHANNELINFOREQUEST \- 
.PP
Channel info request body.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nmxp_chan.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBkey\fP"
.br
.ti -1c
.RI "int32_t \fBignored\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Channel info request body. 
.SH "Member Data Documentation"
.PP 
.SS "int32_t \fBNMXP_CHANNELINFOREQUEST::key\fP"
.SS "int32_t \fBNMXP_CHANNELINFOREQUEST::ignored\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libnmxp from the source code.
