.TH "NMXP_RAW_STREAM_DATA" 3 "Mon Jan 24 2011" "Version 1.2.4" "libnmxp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NMXP_RAW_STREAM_DATA \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nmxp.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBlast_seq_no_sent\fP"
.br
.ti -1c
.RI "double \fBlast_sample_time\fP"
.br
.ti -1c
.RI "double \fBlast_latency\fP"
.br
.ti -1c
.RI "int32_t \fBmax_pdlist_items\fP"
.br
.ti -1c
.RI "double \fBmax_tolerable_latency\fP"
.br
.ti -1c
.RI "int \fBtimeoutrecv\fP"
.br
.ti -1c
.RI "int32_t \fBn_pdlist\fP"
.br
.ti -1c
.RI "\fBNMXP_DATA_PROCESS\fP ** \fBpdlist\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int32_t \fBNMXP_RAW_STREAM_DATA::last_seq_no_sent\fP"
.SS "double \fBNMXP_RAW_STREAM_DATA::last_sample_time\fP"
.SS "double \fBNMXP_RAW_STREAM_DATA::last_latency\fP"
.SS "int32_t \fBNMXP_RAW_STREAM_DATA::max_pdlist_items\fP"
.SS "double \fBNMXP_RAW_STREAM_DATA::max_tolerable_latency\fP"
.SS "int \fBNMXP_RAW_STREAM_DATA::timeoutrecv\fP"
.SS "int32_t \fBNMXP_RAW_STREAM_DATA::n_pdlist\fP"
.SS "\fBNMXP_DATA_PROCESS\fP** \fBNMXP_RAW_STREAM_DATA::pdlist\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libnmxp from the source code.
