.TH "NMXP_CHAN_PRECISLIST" 3 "Mon Jan 24 2011" "Version 1.2.4" "libnmxp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NMXP_CHAN_PRECISLIST \- 
.PP
Precis Channel list.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nmxp_chan.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBnumber\fP"
.br
.ti -1c
.RI "\fBNMXP_CHAN_PRECISITEM\fP \fBchannel\fP [MAX_N_CHAN]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Precis Channel list. 
.SH "Member Data Documentation"
.PP 
.SS "int32_t \fBNMXP_CHAN_PRECISLIST::number\fP"
.SS "\fBNMXP_CHAN_PRECISITEM\fP \fBNMXP_CHAN_PRECISLIST::channel\fP[MAX_N_CHAN]"

.SH "Author"
.PP 
Generated automatically by Doxygen for libnmxp from the source code.
