.TH "NMXP_DATA_REQUEST" 3 "Mon Jan 24 2011" "Version 1.2.4" "libnmxp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NMXP_DATA_REQUEST \- 
.PP
Body of DataRequest message.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nmxp.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBchan_key\fP"
.br
.ti -1c
.RI "int32_t \fBstart_time\fP"
.br
.ti -1c
.RI "int32_t \fBend_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Body of DataRequest message. 
.SH "Member Data Documentation"
.PP 
.SS "int32_t \fBNMXP_DATA_REQUEST::chan_key\fP"
.SS "int32_t \fBNMXP_DATA_REQUEST::start_time\fP"
.SS "int32_t \fBNMXP_DATA_REQUEST::end_time\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libnmxp from the source code.
