.TH "todo" 3 "Mon Jan 24 2011" "Version 1.2.4" "libnmxp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- .TH "todo" 3 "Mon Jan 24 2011" "Version 1.2.4" "libnmxp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \-  
.IP "\fBPage \fBlibnmxp and nmxptool: open-source software for Nanometrics data acquisition\fP \fP" 1c
.IP "\(bu" 2
Extend english version
.PP
.PP
.PP
 
.IP "\fBPage \fBlibnmxp e nmxptool: software open-source per trasmissioni dati sismici Nanometrics\fP \fP" 1c
.IP "\(bu" 2
Sorgente 1. Struttura base in C che implementa D.A.P. versione 1.0 utilizzando le APIs di libnmxp.
.IP "\(bu" 2
Sorgente 2. Struttura base in C che implementa P.D.S. versione 1.4 utilizzando le APIs di libnmxp.
.PP
.PP
.IP "\(bu" 2
Tabella 2. Report sintetico relativo ai dati archiviati dei canali in test il 22 settembre 2007 tramite nmxptool e seedllink.
.IP "\(bu" 2
Tabella 3. Report sintetico relativo ai dati archiviati dei canali in test il 23 settembre 2007 tramite nmxptool e seedllink.
.PP
.PP

