//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by common.rc
//
#define IDR_PHASEMENU                   329
#define IDD_WAITDLG                     339
#define IDI_HEARTBEAT_GREEN_1           501
#define IDI_HEARTBEAT_PRIMARY_GREEN_1   501
#define IDI_HEARTBEAT_NONE_1            502
#define IDI_HEARTBEAT_PRIMARY_NONE_1    502
#define IDI_HEARTBEAT_NONE_2            503
#define IDI_HEARTBEAT_PRIMARY_NONE_2    503
#define IDI_HEARTBEAT_NONE_3            504
#define IDI_HEARTBEAT_PRIMARY_NONE_3    504
#define IDI_HEARTBEAT_NONE_4            505
#define IDI_HEARTBEAT_PRIMARY_NONE_4    505
#define IDI_HEARTBEAT_GREEN_NOCONN      507
#define IDI_HEARTBEAT_PRIMARY_GREEN_NOCONN 507
#define IDI_HEARTBEAT_NONE_NOCONN       508
#define IDI_HEARTBEAT_PRIMARY_NONE_NOCONN 508
#define IDI_HEARTBEAT_RED_NOCONN        509
#define IDI_HEARTBEAT_PRIMARY_RED_NOCONN 509
#define IDI_HEARTBEAT_YELLOW_NOCONN     510
#define IDI_HEARTBEAT_PRIMARY_YELLOW_NOCONN 510
#define IDI_HEARTBEAT_SECONDARY_GREEN_1 511
#define IDI_HEARTBEAT_SECONDARY_GREEN_2 512
#define IDI_HEARTBEAT_SECONDARY_GREEN_3 513
#define IDI_HEARTBEAT_SECONDARY_GREEN_4 514
#define IDI_HEARTBEAT_SECONDARY_GREEN_NOCONN 515
#define IDI_HEARTBEAT_SECONDARY_NONE_1  516
#define IDI_HEARTBEAT_SECONDARY_NONE_2  517
#define IDI_HEARTBEAT_SECONDARY_NONE_3  518
#define IDI_HEARTBEAT_SECONDARY_NONE_4  519
#define IDI_HEARTBEAT_SECONDARY_NONE_NOCONN 520
#define IDI_HEARTBEAT_SECONDARY_RED_1   521
#define IDI_HEARTBEAT_SECONDARY_RED_2   522
#define IDI_HEARTBEAT_SECONDARY_RED_3   523
#define IDI_HEARTBEAT_SECONDARY_RED_4   524
#define IDI_HEARTBEAT_SECONDARY_RED_NOCONN 525
#define IDI_HEARTBEAT_SECONDARY_YELLOW_1 526
#define IDI_HEARTBEAT_SECONDARY_YELLOW_2 527
#define IDI_HEARTBEAT_SECONDARY_YELLOW_3 528
#define IDI_HEARTBEAT_SECONDARY_YELLOW_4 529
#define IDI_HDR_PRISORT_UP              530
#define IDI_HDR_PRISORT_DOWN            531
#define IDI_HDR_SECONDSORT_UP           532
#define IDI_HDR_SECONDSORT_DOWN         533
#define IDI_HEARTBEAT_GREEN_2           534
#define IDI_HEARTBEAT_PRIMARY_GREEN_2   534
#define IDI_HEARTBEAT_GREEN_3           535
#define IDI_HEARTBEAT_PRIMARY_GREEN_3   535
#define IDI_HEARTBEAT_GREEN_4           536
#define IDI_HEARTBEAT_PRIMARY_GREEN_4   536
#define IDI_HEARTBEAT_YELLOW_1          537
#define IDI_HEARTBEAT_PRIMARY_YELLOW_1  537
#define IDI_HEARTBEAT_YELLOW_2          538
#define IDI_HEARTBEAT_PRIMARY_YELLOW_2  538
#define IDI_HEARTBEAT_YELLOW_3          539
#define IDI_HEARTBEAT_PRIMARY_YELLOW_3  539
#define IDI_HEARTBEAT_YELLOW_4          540
#define IDI_HEARTBEAT_PRIMARY_YELLOW_4  540
#define IDI_HEARTBEAT_RED_1             541
#define IDI_HEARTBEAT_PRIMARY_RED_1     541
#define IDI_HEARTBEAT_RED_2             542
#define IDI_HEARTBEAT_PRIMARY_RED_2     542
#define IDI_HEARTBEAT_RED_3             543
#define IDI_HEARTBEAT_PRIMARY_RED_3     543
#define IDI_HEARTBEAT_RED_4             544
#define IDI_HEARTBEAT_PRIMARY_RED_4     544
#define IDI_HEARTBEAT_SECONDARY_YELLOW_NOCONN 545
#define IDD_LOC_SUMM_DIALOG             546
#define IDC_PROGRESS                    1247
#define IDC_LATITUDE_TITLE              5000
#define IDC_LONGITUDE_TITLE             5001
#define IDC_DEPTH_TITLE                 5002
#define IDC_ORIGIN_TIME_TITLE           5003
#define IDC_REGION_NAME_TITLE           5004
#define IDC_ELAPSED_TIME_TITLE          5005
#define IDC_NUMBER_PHASES_TITLE         5006
#define IDC_GAP_TITLE                   5007
#define IDC_MINIMUM_DISTANCE_TITLE      5008
#define IDC_RMS_TITLE                   5009
#define IDC_LATITUDE_VALUE              5010
#define IDC_LONGITUDE_VALUE             5011
#define IDC_DEPTH_VALUE                 5012
#define IDC_LATITUDE_ERROR_TITLE        5013
#define IDC_LONGITUDE_ERROR_TITLE       5014
#define IDC_DEPTH_ERROR_TITLE           5015
#define IDC_LATITUDE_ERROR_VALUE        5016
#define IDC_LONGITUDE_ERROR_VALUE       5017
#define IDC_DEPTH_ERROR_VALUE           5018
#define IDC_ORIGIN_TIME_VALUE           5019
#define IDC_REGION_NAME_VALUE           5020
#define IDC_ELAPSED_TIME_VALUE          5021
#define IDC_NUMBER_PHASES_VALUE         5022
#define IDC_GAP_VALUE                   5023
#define IDC_MINIMUM_DISTANCE_VALUE      5024
#define IDC_RMS_VALUE                   5025
#define IDC_LOCATION_SUMMARY_TITLE      5026
#define IDC_MAG_LOCATION_SUMMARY_TITLE  5027
#define IDC_LOC_SUMM_LOC_MODE           5028
#define IDC_LOC_SUMM_MAG_MODE           5029
#define ID_PHASEMENUITEMBLANKTEXT       32871

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        547
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         5030
#define _APS_NEXT_SYMED_VALUE           501
#endif
#endif
