# ----------------------------------------------------------------------
# MakeFile for adsend
# ----------------------------------------------------------------------
#
# Instructions on how to create the executable:
#
#     First make sure that your environmental variables
#     'INCLUDE' and 'LIB' are set correctly.
#
#     You may also load this .MAK file from Visual C++.
#     Visual C++ will then treat it as an 'external makefile'.
#
#     The libsrc functions are recompiled here because we need
#     single-threaded versions instead of multi-threaded versions
#
#
NODEBUG=1
#
!include <ntwin32.mak>

CFLAGS= $(CFLAGS) $(GLOBALFLAGS)
#
B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib
U = $(EW_HOME)\$(EW_VERSION)\src\libsrc\util
W = $(EW_HOME)\$(EW_VERSION)\src\libsrc\winnt
#
O = SaraAdSend.obj getconfig.obj SaraUtils.obj
J = $L\libew.lib
#
# TARGET: Console application
#
all: SaraAdSend.exe
#
SaraAdSend.exe: $O
    link libcmt.lib /OUT:$B\SaraAdSend.exe $O $J
#    
.c.obj:
    cl /c /DWIN32 $(cvarsmt) $(CFLAGS) $(tflags) $<
#
# Clean-up directives
clean:
    -del *.obj

clean_bin:
    -del $B\SaraAdSend*
