
#
#                    Nmake File For runwws
#                      Windows NT version
#
NODEBUG=1

!include <ntwin32.mak>

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

$B\runwws.exe: runwws.obj pipe_nt.obj
    $(link) $(conlflags) $(ldebug) $(conlibsmt) runwws.obj \
    pipe_nt.obj $L\libew.lib \
    -out:$B\runwws.exe

.c.obj:
   $(CC) $(GLOBALFLAGS)  /nologo $(cflags) $(cdebug) $(cvarsmt) $(tflags) $<

# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~

clean_bin:
	-del $B\runwws*
