
-- sismap

GRANT EXECUTE ON PROCEDURE __DATABASENAME__.`sp_ew_last_event_id` TO '__USERNAME__'@'__HOSTNAME__';
GRANT EXECUTE ON PROCEDURE __DATABASENAME__.`sp_ew_event` TO '__USERNAME__'@'__HOSTNAME__';
GRANT EXECUTE ON PROCEDURE __DATABASENAME__.`sp_ew_event_instance` TO '__USERNAME__'@'__HOSTNAME__';
GRANT EXECUTE ON PROCEDURE __DATABASENAME__.`sp_ew_instance` TO '__USERNAME__'@'__HOSTNAME__';

